# Generated by Django 4.0.3 on 2022-03-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], default='M', max_length=10)),
                ('Phone', models.CharField(max_length=15)),
                ('Weight', models.FloatField(max_length=5)),
                ('Height', models.FloatField(max_length=5)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
