# Generated by Django 4.0.3 on 2022-03-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Height',
            field=models.FloatField(help_text='Enter your height in Cm', max_length=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='Weight',
            field=models.FloatField(help_text='Enter your weight in kgs', max_length=5),
        ),
    ]
