# Generated by Django 4.0.3 on 2022-04-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0010_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Inbody',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
