# Generated by Django 4.0.3 on 2022-04-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0011_person_inbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Inbody',
        ),
    ]
